export enum ComponentName {
  CARDS_GRID = `cards-grid`,
  COLLAGE_WITH_LINK = `collage-with-link`,
  COLLAGE_WITH_TITLE = `collage-with-title`,
  FOOTER = `footer`,
  HEADER = `header`,
  MOBILE_MENU = `mobile-menu`,
  HERO = `hero`,
  PROJECTS_WITH_FOUR_CARDS = `projects-with-four-cards`,
  PROJECTS_WITH_THREE_CARDS = `projects-with-three-cards`,
  PROJECTS_WITH_TEXT_BLOCK = `projects-with-text-block`,
  SERVICES = `services`,
  SIGNPOST_MULTIPLE = `signpost-multiple`,
  SINGLE_IMAGE = `single-image`,
  FORM_BLOCK = `form-block`,
  SUBMITTED_FORM_BLOCK = `submitted-form-block`,
  COOKIE = `cookie`,
  NOT_FOUND = `not-found`,
  FORM_MODAL = `form-modal`,
  SUBMITTED_FORM_MODAL = `submitted-form-modal`,
}
