export const getSkills = (t: any) => [
  {
    title: t('Backend.title'),
    scope: [
      '.Net Core 3-6',
      'C#',
      'Node.js',
      'JavaScript',
      'NestJS',
      'TypeScript',
      'FastAPI',
      'Python',
      'Kubernetes',
      'Docker',
      'PostgreSQL',
    ],
    services: t('Backend.services', { returnObjects: true }),
    technologies: [
      '.NET Core',
      'EF Core',
      'Node.js',
      'NestJS',
      'Flask',
      'SQLAlchemy',
      'Solidity',
      'PostgreSQL',
      'MS SQL Server',
      'MySQL',
      'MongoDB',
      'ClickHouse',
      'RabbitMQ',
      'Redis',
      'S3',
      'Docker',
      'Kubernetes',
      'Helm',
      'Terraform',
      'Azure',
      'AWS',
      'Azure DevOps',
      'GitHub Actions',
      'Gitlab CI',
      'Nginx',
      'Postman',
      'WireShark',
    ],
  },
  {
    title: t('Frontend.title'),
    scope: ['JavaScript', 'TypeScript', 'React', 'NextJS', 'Vue', 'BEM'],
    services: t('Frontend.services', { returnObjects: true }),
    technologies: [
      'HTML',
      'CSS',
      'SCSS',
      'JavaScript',
      'TypeScript',
      'React',
      'Create React App',
      'NextJS',
      'VueJS',
      'Vuex',
      'Pinia',
      'Redux Toolkit',
      'MobX',
      'Storyblok',
      'BEM',
    ],
  },
  {
    title: t('QA.title'),
    scope: ['Postman', 'Cypress', 'Jest'],
    services: t('QA.services', { returnObjects: true }),
    technologies: [
      'Cypress',
      'React Testing Library',
      'Jest',
      'Mocha',
      'Cucumber',
      'Pytest',
      'Robot Framework',
      'Google Test library',
      'xUnit',
      'Selenium',
      'jUnit',
      'Browser Devtools',
      'Swagger',
      'Postman',
      'Azure Test Plans',
      'Gitlab CI',
      'GitHub Actions',
    ],
  },
  {
    title: t('Machine.title'),
    scope: [
      'Python',
      'Sklearn',
      'Pandas',
      'Numpy',
      'OpenCV',
      'PyTorch',
      'TensorFlow',
      'Keras',
    ],
    services: t('Machine.services', { returnObjects: true }),
    technologies: [
      'Classical Machine Learning',
      'Neural Networks',
      'Computer Vision',
      'Natural Language Processing',
      'Data Analysis',
      'Reinforcement Learning',
      'PyTorch',
      'Tensorflow/Keras',
      'NumPy',
      'OpenCV',
      'Pandas',
      'Transfer Learning',
      'Matplotlib',
      'Seaborn',
      'Scikit Learn',
    ],
  },
  {
    title: t('UI/UX.title'),
    scope: ['Figma', 'Adobe XD', 'Photoshop'],
    services: t('UI/UX.services', { returnObjects: true }),
    technologies: [
      'Figma',
      'Adobe XD',
      'Photoshop',
      'Illustrator',
      'Blender',
      'Webflow',
      'Tilda',
    ],
  },
];
