name: Linting check

on: 
  pull_request:
    branches: [develop, feature/*]

jobs:
  build:

    runs-on: ubuntu-20.18.0

    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run CI command
      run: npm ci

    - name: Check linting
      run: npm run lint


